USE API_CALLING_SP;
DELIMITER //
CREATE TRIGGER TR_BEFORE_INSERT_ACCOUNTS
BEFORE INSERT ON ACCOUNTS 
FOR EACH ROW
BEGIN
DECLARE ACC_STATUS BOOLEAN ;
IF NEW.BALANCE = 0 THEN
SET NEW.ACC_STATUS ='0' ;
END IF ;
END //
DELIMITER ;

DROP  TRIGGER TR_BEFORE_INSERT_ACCOUNTS;
