USE BANK_SYSTEM;
-- CREATE TABLE BANK_BRANCH --
DELIMITER //
CREATE  PROCEDURE SP_CREATE_TABLE_BANK_BRANCH()
BEGIN
CREATE TABLE BANK_BRANCH(
BRANCH_ID INT PRIMARY KEY ,
  BANK_NAME VARCHAR(255),
  IFSC_CODE VARCHAR(255),
  ADDRESS VARCHAR(255),
  CITY VARCHAR(255),
  STATE VARCHAR(255),
  MANAGER_ID INT);
END //
DELIMITER ;
-- CALL PRO --
CALL  SP_CREATE_TABLE_BANK_BRANCH;

-- CREATE TABLE EMPLOYEE --
DELIMITER //
CREATE PROCEDURE SP_CREATE_TABLE_EMPLOYEE()
BEGIN
CREATE TABLE EMPLOYEE(
  EMP_ID INT PRIMARY KEY,
  EMP_NAME VARCHAR(255),
  EMP_ADDRESS VARCHAR(255),
  BRANCH_ID INT ,
  DEPARTMENT_ID INT,
  ACC_NO INT,
  FOREIGN KEY(BRANCH_ID) REFERENCES BANK_BRANCH(BRANCH_ID),
  FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
  FOREIGN KEY(ACC_NO) REFERENCES ACCOUNTS(ACC_NO)
);
END //
DELIMITER ;

-- CALL PRO --
CALL SP_CREATE_TABLE_EMPLOYEE;

 -- CREATE TABLE DEPARTMENT --
 DELIMITER //
 CREATE PROCEDURE SP_CREATE_TABLE_DEPARTMENT()
 CREATE TABLE DEPARTMENT(
  DEPARTMENT_ID INT PRIMARY KEY ,
  DEPARTMENT_NAME VARCHAR(255),
  HEAD_OF_DEPARTMENT INT,
  DESIGNATION VARCHAR(255)
);
END //
DELIMITER ;

-- CALL DEPARTMENT --
CALL SP_CREATE_TABLE_DEPARTMENT;

-- CREATE TABLE CUSTOMER --
 DELIMITER //
 CREATE PROCEDURE SP_CREATE_TABLE_CUSTOMER()
 BEGIN
CREATE TABLE CUSTOMER(
CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(255) ,
CUSTOMER_ADDRESS VARCHAR(255),
BRANCH_ID INT,
ACC_NO INT,
FOREIGN KEY(BRANCH_ID) REFERENCES BANK_BRANCH(BRANCH_ID),
FOREIGN KEY(ACC_NO) REFERENCES ACCOUNTS(ACC_NO)
);
END //
DELIMITER ;
-- CALL PRO --
CALL SP_CREATE_TABLE_CUSTOMER;

-- CREATE TABLE ACCOUNTS --
 DELIMITER //
 CREATE PROCEDURE SP_CREATE_TABLE_ACCOUNTS()
 BEGIN
CREATE TABLE ACCOUNTS(
  ACC_NO INT PRIMARY KEY,
  BRANCH_ID INT,
  CUSTOMER_ID INT,
  ACC_TYPE VARCHAR(255),
  BALANCE DECIMAL,
  ACC_STATUS BOOLEAN,
  FOREIGN KEY(BRANCH_ID) REFERENCES BANK_BRANCH(BRANCH_ID),
  FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
END //
DELIMITER ;

-- CALL PRO --
CALL SP_CREATE_TABLE_ACCOUNTS;

--  CREATE TABLE TRANSACTION --
DELIMITER //
CREATE PROCEDURE SP_CREATE_TABLE_TRANSACTION()
BEGIN
CREATE TABLE TRANSACTION(
  ACC_NO INT PRIMARY KEY,
  DATE_TIME_STAMP datetime,
  EMP_ID INT,
  CREDIT_OR_DEPOSIT VARCHAR(255),
  TRANSACTION_TYPE VARCHAR(255),
  FOREIGN KEY(ACC_NO) REFERENCES ACCOUNTS(ACC_NO),
  FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);
END //
DELIMITER ;
 
 -- CALL PRO --
 CALL SP_CREATE_TABLE_TRANSACTION;

