USE API_CALLING_SP;
DELIMITER //
CREATE PROCEDURE SP_GET_ACCOUNTS()
BEGIN
SELECT * FROM ACCOUNTS ;
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_GET_BANK_BRANCH()
BEGIN
SELECT * FROM BANK_BRANCH ;
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_GET_EMPLOYEE()
BEGIN
SELECT * FROM EMPLOYEE ;
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_GET_DEPARTMENT()
BEGIN
SELECT * FROM DEPARTMENT ;
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_GET_CUSTOMER()
BEGIN
SELECT * FROM CUSTOMER ;
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_GET_TRANSACTION()
BEGIN
SELECT * FROM TRANSACTION ;
END // 
DELIMITER ;