
USE API_CALLING_SP;
--
DELIMITER //
CREATE PROCEDURE SP_ADD_BANK_BRANCH(BRANCH_ID INT,
  BANK_NAME VARCHAR(255),
  IFSC_CODE VARCHAR(255),
  ADDRESS VARCHAR(255),
  CITY VARCHAR(255),
  STATE VARCHAR(255),
  MANAGER_ID INT)
BEGIN
INSERT INTO BANK_BRANCH VALUES
(BRANCH_ID ,BANK_NAME ,IFSC_CODE ,ADDRESS,CITY,STATE ,MANAGER_ID );
END // 
DELIMITER ;
--

DELIMITER //
CREATE PROCEDURE SP_ADD_EMPLOYEE( 
  EMP_ID INT,
  EMP_NAME VARCHAR(255),
  EMP_ADDRESS VARCHAR(255),
  BRANCH_ID INT ,
  DEPARTMENT_ID INT,
  ACC_NO INT)
BEGIN
INSERT INTO EMPLOYEE VALUES(EMP_ID,EMP_NAME ,EMP_ADDRESS,BRANCH_ID ,DEPARTMENT_ID, ACC_NO );
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_ADD_DEPARTMENT(
  DEPARTMENT_ID INT ,
  DEPARTMENT_NAME VARCHAR(255),
  HEAD_OF_DEPARTMENT INT,
  DESIGNATION VARCHAR(255)
)
BEGIN
INSERT INTO DEPARTMENT VALUES(
  DEPARTMENT_ID ,
  DEPARTMENT_NAME ,
  HEAD_OF_DEPARTMENT,
  DESIGNATION );
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_ADD_CUSTOMER(
CUSTOMER_ID INT,
CUSTOMER_NAME VARCHAR(255) ,
CUSTOMER_ADDRESS VARCHAR(255),
BRANCH_ID INT,
ACC_NO INT)
BEGIN
INSERT INTO CUSTOMER VALUES(
CUSTOMER_ID ,
CUSTOMER_NAME ,
CUSTOMER_ADDRESS ,
BRANCH_ID ,
ACC_NO );
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_ADD_ACCOUNTS(ACC_NO INT  ,
  BRANCH_ID INT,
  CUSTOMER_ID INT,
  ACC_TYPE VARCHAR(255),
  BALANCE DECIMAL,
  ACC_STATUS BOOLEAN)
BEGIN
INSERT INTO ACCOUNTS VALUES(ACC_NO ,
  BRANCH_ID ,
  CUSTOMER_ID ,
  ACC_TYPE ,
  BALANCE ,
  ACC_STATUS );
END // 
DELIMITER ;
--

DELIMITER //
CREATE PROCEDURE SP_ADD_TRANSACTION(ACC_NO INT ,
  DATE_TIME_STAMP datetime,
  EMP_ID INT,
  CREDIT_OR_DEPOSIT VARCHAR(255),
  TRANSACTION_TYPE VARCHAR(255))
BEGIN
INSERT INTO TRANSACTION VALUES(ACC_NO ,
 DATE_TIME_STAMP ,
 EMP_ID ,
 CREDIT_OR_DEPOSIT ,
 TRANSACTION_TYPE );
END // 
DELIMITER ;