
USE API_CALLING_SP;
--
DELIMITER //
CREATE PROCEDURE SP_ADD_BANK_BRANCH(BRANCH_ID INT,
  BANK_NAME VARCHAR(255),
  IFSC_CODE VARCHAR(255),
  ADDRESS VARCHAR(255),
  CITY VARCHAR(255),
  STATE VARCHAR(255),
  MANAGER_ID INT)
BEGIN
INSERT INTO BANK_BRANCH VALUES
(BRANCH_ID ,BANK_NAME ,IFSC_CODE ,ADDRESS,CITY,STATE ,MANAGER_ID );
END // 
DELIMITER ;
--

DELIMITER //
CREATE PROCEDURE SP_ADD_EMPLOYEE()
BEGIN
SELECT * FROM EMPLOYEE ;
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_ADD_DEPARTMENT()
BEGIN
SELECT * FROM DEPARTMENT ;
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_ADD_CUSTOMER()
BEGIN
SELECT * FROM CUSTOMER ;
END // 
DELIMITER ;
--
DELIMITER //
CREATE PROCEDURE SP_ADD_ACCOUNTS()
BEGIN
SELECT * FROM ACCOUNTS ;
END // 
DELIMITER ;
--

DELIMITER //
CREATE PROCEDURE SP_ADD_TRANSACTION()
BEGIN
SELECT * FROM TRANSACTION ;
END // 
DELIMITER ;