USE API_CALLING_SP;
DELIMITER //
CREATE TRIGGER TR_BEFORE_INSERT_ACCOUNTS
BEFORE INSERT ON ACCOUNTS 
FOR EACH ROW
BEGIN
DECLARE ACC_STATUS BOOLEAN ;
IF NEW.BALANCE = 0 THEN
SET NEW.ACC_STATUS ='0' ;
END IF ;
END //
DELIMITER ;

DROP  TRIGGER TR_BEFORE_INSERT_ACCOUNTS;

DELIMITER //
CREATE TRIGGER TR_BEFORE_INSERT_ACCOUNTS_NO
BEFORE INSERT ON ACCOUNTS 
FOR EACH ROW
BEGIN
DECLARE MESSAGE_TEXT VARCHAR(200);
-- DECLARE ACC_NO INT ;
DECLARE ACC_NO_LENGTH INT ;
SET ACC_NO_LENGTH = (SELECT LENGTH (NEW.ACC_NO));
IF  ACC_NO_LENGTH = 5 THEN
SET  MESSAGE_TEXT ='OK.';
ELSE
SET  MESSAGE_TEXT ='PLEASE CHECK THE ACCOUNT DETAILS.';
END IF ;
END //
DELIMITER ;
INSERT INTO ACCOUNTS VALUES(543111047,1,1,'SAVINGS',12000,1);
DROP TRIGGER TR_BEFORE_INSERT_ACCOUNTS_NO
