USE API_CALLING_SP;
DELIMITER //
CREATE PROCEDURE SP_EMPLOYEE_GROUP_BY_DEPARTMENT_ID()
BEGIN
SELECT EMP_ID,DEPARTMENT_ID,COUNT(DEPARTMENT_ID) FROM EMPLOYEE GROUP BY DEPARTMENT_ID;
END //
DELIMITER ;
CALL SP_EMPLOYEE_GROUP_BY_DEPARTMENT_ID;

DELIMITER //
CREATE PROCEDURE SP_COUNT_CUSTOMER_ID()
BEGIN
SELECT CUSTOMER_ID,COUNT(CUSTOMER_ID)AS TOTAL_CUSTOMERS FROM CUSTOMER;
END //
DELIMITER ;
CALL SP_COUNT_CUSTOMER_ID;

DELIMITER //
CREATE PROCEDURE SP_ACCOUNTS_COUNT_ACC_TYPE()
BEGIN
SELECT BRANCH_ID,ACC_TYPE,COUNT(ACC_TYPE) FROM ACCOUNTS GROUP BY ACC_TYPE,BRANCH_ID ;
END //
DELIMITER ;
CALL SP_ACCOUNTS_GROUP_BY_ACC_TYPE;


SELECT BRANCH_ID,ACC_TYPE,BALANCE,COUNT(ACC_TYPE) FROM ACCOUNTS GROUP BY ACC_TYPE,BRANCH_ID HAVING BALANCE > 12000  ;













