USE API_CALLING_SP;

-- JOIN_BANK_BRANCH_ACCOUNTS --

DELIMITER //
CREATE PROCEDURE SP_JOIN_BANK_BRANCH_ACCOUNTS()
BEGIN
SELECT BANK_BRANCH.BRANCH_ID,
BANK_BRANCH.BANK_NAME,
BANK_BRANCH.IFSC_CODE,
BANK_BRANCH.ADDRESS,
BANK_BRANCH.CITY,
ACCOUNTS.ACC_NO,
ACCOUNTS.CUSTOMER_ID,
ACCOUNTS.ACC_TYPE,
ACCOUNTS.ACC_STATUS
FROM BANK_BRANCH 
INNER JOIN ACCOUNTS 
ON 
BANK_BRANCH.BRANCH_ID = ACCOUNTS.BRANCH_ID;
END //
DELIMITER ;

-- JOIN_EMPLOYEE_DEPARTMENT --

DELIMITER //
CREATE PROCEDURE SP_JOIN_EMPLOYEE_DEPARTMENT()
BEGIN
SELECT 
EMPLOYEE.EMP_ID,
EMPLOYEE.EMP_NAME,
EMPLOYEE.DEPARTMENT_ID,
DEPARTMENT.DEPARTMENT_NAME,
DEPARTMENT.DESIGNATION
FROM EMPLOYEE
INNER JOIN DEPARTMENT 
ON 
EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
ORDER BY EMPLOYEE.EMP_ID;
END //
DELIMITER ;

-- JOIN_EMPLOYEE_TRANSACTION

DELIMITER //
CREATE PROCEDURE SP_JOIN_EMPLOYEE_TRANSACTION()
BEGIN
SELECT 
EMPLOYEE.EMP_ID,
EMPLOYEE.EMP_NAME,
TRANSACTION.DATE_TIME_STAMP,
TRANSACTION.TRANSACTION_TYPE
FROM EMPLOYEE
INNER JOIN TRANSACTION
ON 
EMPLOYEE.EMP_ID = TRANSACTION.EMP_ID;
END //
DELIMITER ;

-- JOIN_ACCOUNTS_CUSTOMER

DELIMITER //
CREATE PROCEDURE SP_JOIN_ACCOUNTS_CUSTOMER()
BEGIN
SELECT
CUSTOMER.CUSTOMER_ID,
CUSTOMER.CUSTOMER_NAME,
CUSTOMER.ACC_NO,
ACCOUNTS.BALANCE,
ACCOUNTS.ACC_STATUS,
ACCOUNTS.ACC_TYPE
FROM CUSTOMER
INNER JOIN ACCOUNTS
ON
CUSTOMER.ACC_NO=ACCOUNTS.ACC_NO;
END //
DELIMITER ;

-- JOIN_BANK_BRANCH_ACCOUNTS__CUSTOMER

DELIMITER //
CREATE PROCEDURE SP_JOIN_BANK_BRANCH_ACCOUNTS_CUSTOMER()
BEGIN
SELECT 
CUSTOMER.CUSTOMER_ID,
CUSTOMER.CUSTOMER_NAME,
BANK_BRANCH.BRANCH_ID,
BANK_BRANCH.BANK_NAME,
BANK_BRANCH.IFSC_CODE,
BANK_BRANCH.CITY,
CUSTOMER.ACC_NO,
ACCOUNTS.BALANCE,
ACCOUNTS.ACC_STATUS,
ACCOUNTS.ACC_TYPE
FROM CUSTOMER 
INNER JOIN ACCOUNTS 
ON
CUSTOMER.CUSTOMER_ID = ACCOUNTS.CUSTOMER_ID 
INNER JOIN BANK_BRANCH ON
BANK_BRANCH.BRANCH_ID = ACCOUNTS.BRANCH_ID
ORDER BY CUSTOMER.CUSTOMER_ID ;
END //
DELIMITER ;

-- JOIN_BANK_BRANCH_ACCOUNTS_CUSTOMER_EMPLOYEE_TRANSACTION_DEPARTMENT

DELIMITER //
CREATE PROCEDURE SP_JOIN_ALL_TABLES()
BEGIN
SELECT  
BANK_BRANCH.BRANCH_ID,
BANK_BRANCH.BANK_NAME,
BANK_BRANCH.CITY,
EMPLOYEE.EMP_ID,
EMPLOYEE.EMP_NAME,
EMPLOYEE.DEPARTMENT_ID,
DEPARTMENT.DEPARTMENT_NAME,
DEPARTMENT.DESIGNATION


FROM BANK_BRANCH
INNER JOIN EMPLOYEE ON
 BANK_BRANCH.BRANCH_ID = EMPLOYEE.BRANCH_ID 
 
INNER JOIN DEPARTMENT ON
EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID ;

END //
DELIMITER ;