USE WORLD ;
SELECT *, COUNT(COUNTRYCODE) AS COUNT_COUNTRY_CODE FROM CITY GROUP BY District  HAVING COUNTRYCODE = 'NLD';

SELECT CITY.ID,CITY.NAME,CITY.COUNTRYCODE,COUNTRYLANGUAGE.LANGUAGE,COUNTRYLANGUAGE.PERCENTAGE FROM CITY INNER JOIN 
COUNTRYLANGUAGE ON
CITY.COUNTRYCODE=COUNTRYLANGUAGE.COUNTRYCODE
GROUP BY CITY.NAME ;

SELECT CITY.ID,CITY.NAME,CITY.COUNTRYCODE,COUNTRYLANGUAGE.LANGUAGE,COUNTRYLANGUAGE.PERCENTAGE FROM CITY LEFT JOIN 
COUNTRYLANGUAGE ON
CITY.COUNTRYCODE=COUNTRYLANGUAGE.COUNTRYCODE
GROUP BY CITY.NAME ;

SELECT LANGUAGE,COUNT(LANGUAGE)FROM COUNTRYLANGUAGE GROUP BY LANGUAGE;

SELECT LANGUAGE,IsOfficial,COUNT(LANGUAGE)FROM COUNTRYLANGUAGE GROUP BY LANGUAGE HAVING IsOfficial = 'F';

SELECT COUNTRY.NAME,COUNTRY.CONTINENT,COUNTRY.REGION, COUNTRYLANGUAGE.COUNTRYCODE,COUNTRYLANGUAGE.LANGUAGE,COUNTRYLANGUAGE.PERCENTAGE,CITY.ID,CITY.NAME FROM COUNTRY
INNSER JOIN COUNTRYLANGUAGE ON 
COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE;
